apiVersion: v1
entries:
  mysql:
  - apiVersion: v1
    appVersion: 5.7.27
    created: "2019-11-30T20:47:41.385886+01:00"
    description: Fast, reliable, scalable, and easy to use open-source relational
      database system.
    digest: 935e482f45a1f45d78ea8bfbe4883158b92ba84efba396789de493537503325a
    engine: gotpl
    home: https://www.mysql.com/
    icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
    keywords:
    - mysql
    - database
    - sql
    maintainers:
    - email: o.with@sportradar.com
      name: olemarkus
    - email: viglesias@google.com
      name: viglesiasce
    name: mysql
    sources:
    - https://github.com/kubernetes/charts
    - https://github.com/docker-library/mysql
    urls:
    - https://raw.githubusercontent.com/crhuber/golinks/master/helm/golinks/charts/mysql-1.4.0.tgz
    version: 1.4.0
generated: "2019-11-30T20:47:41.384834+01:00"
