# Default values for golinks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
nameOverride: ""
fullnameOverride: ""

api:
  image:
    repository: crhuber/golinks-api
    tag: latest
    pullPolicy: Always
  containerPort: 5000

frontend:
  image:
    repository:  crhuber/golinks-frontend
    tag: latest
    pullPolicy: Always
  containerPort: 80


resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: golinks.local
      paths: [/]
  tls: []

db:
  create: true

mysql:
  mysqlRootPassword: password
  mysqlUser: admin
  mysqlPassword: password
  mysqlDatabase: golinks
