{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "golinks.fullname" . }}
  labels:
    app: {{ template "golinks.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ default "MISSING" $value | b64enc | quote }}
{{- end }}
{{- end}}