name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push api
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crhuber/golinks-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
    - name: Docker push frontend
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crhuber/golinks-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: frontend
        tag_names: true
        buildargs: VUE_APP_API_BASE_URL=""
