name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Build the api Docker image
    #   run: docker build . --tag crhuber/golinks-api:{{ steps.bump_version_and_push_tag.outputs.new_tag }}
    # - name: Tag api Docker image latest
    #   run: docker tag crhuber/golinks-api:{{ steps.bump_version_and_push_tag.outputs.new_tag }} crhuber/golinks-api:latest
    # - name: Build the frontend Docker image
    #   run: docker build ./frontend/Dockerfile  --build-arg VUE_APP_API_BASE_URL="" --tag crhuber/golinks-frontend:{{ steps.bump_version_and_push_tag.outputs.new_tag }}
    # - name: Tag frontend Docker image latest
    #   run: docker tag crhuber/golinks-frontend:{{ steps.bump_version_and_push_tag.outputs.new_tag }} crhuber/golinks-frontend:latest  
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crhuber/golinks-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true

